  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ../logger/log:/var/custom
      - ./conf:/var/conf
    command: -config.file=/var/conf/prom-config.yml
    networks:
      - loki
  